#!/bin/bash
if [[ $1 == "view" ]]
then
	# Assume bgzip'ed VCF input to plain text for CPSR/PCGR use cases, only canonical chromosomes desired (sorting is messy otherwise).
	bgzip -cd ${!#} | perl -ne 'print if /^#/ or /^(?:chr)?(?:\d+|X|Y|MT|M)\t/'
elif [[ $1 == "sort" ]]
then
	# Assume bgzip'ed VCF input/output and accepting stripped chr prefix for CPSR/PCGR use cases.
	T="$(mktemp)"
	T2="$(mktemp)"
	bgzip -cd ${!#} | sed 's/^chr//' | sed 's/=chr/=/' > $T
	# Print header lines as-is.
       	grep '^#' $T > $T2 
	# Print numerically sorted chromosomes and positions.
	grep -v '^[#MXY]' $T | sort -k1,1n -k2,2n >> $T2 
	# Print M(T), X and Y lexically sorted non-autosomal chromosomes and numerical positions.
	grep -v '^[#0-9]' $T | sort -k1,1 -k2,2n >> $T2 
	bgzip -f $T2
	cat $T2.gz
	rm -f $T $T2 $T2.gz
else
	echo "Usage: $0 <view|sort> [...] input.vcf.gz"
fi
